/* eslint-disable @next/next/no-img-element */
import Head from "next/head";

function Home() {
  return (
    <main className="h-[100svh]">
      <Head>
        <title>Next Pages router starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Next Pages router starter</h1>
    </main>
  );
}

export default Home;
